### ISSUE TITLE
Success report: Apple MacBook Air M1 + Rancher Desktop + ktop

### ISSUE THREAD

**Issue by vielmetti** [vladimirvivien/ktop#18]
OK to close this once reviewed - I want to report that Rancher
Desktop ( https://github.com/rancher-sandbox/rancher-desktop )
works just fine with `ktop` running on a MacBook Air (M1). I 
installed the software with the supplied `brew` instructions,
Thanks for a nifty tool and looking forward to how this develops.

**Comment by vladimirvivien** [comment]
Awesome !!  thank you for taking time to report this 🙏
