### ISSUE TITLE
How to see all info about  node/pod

### ISSUE THREAD

**Issue by orxvan** [vladimirvivien/ktop#20]
the ktop is good,thx to vladimirvivien 

but when I started the ktop, I can only see a part of nodes' info or pods' info,for example, the command only show 4 nodes info, althougth the cluster has 13 nodes, how can I see another 9 nodes' info?

thank you!

**Comment by vladimirvivien** [comment]
Press tab key until the Nodes are selected. Then use arrow up and down to see rest of nodes.

**Comment by orxvan** [comment]
thank you! It worked!
