### ISSUE TITLE
New release for packaging purposes

### ISSUE THREAD

**Issue by ivankovnatsky** [vladimirvivien/ktop#37]
Can you please release/tag latest changes so that it could be easy to grab the version instead of commit hash. Thanks.

**Comment by vladimirvivien** [comment]
Yes, it's coming out this weekend. 
Busy lately, but it's coming 😄

**Comment by vladimirvivien** [comment]
Also @ivankovnatsky thank you for your interest in/using the project 👍 
I did try to release last weekend but go-releaser broke after upgrading it.
Will give it another try this weekend.
