### ISSUE TITLE
Overview screen not updating

### ISSUE THREAD

**Issue by vladimirvivien** [vladimirvivien/ktop#4]
Panels on the overview screens not updating properly.
1) Since resource pod (, node, etc) events are triggered by controllers, it seems the metrics dot update if ctrlr not firing
2) When resources are removed, the panels are not updating their lists properly

**Comment by LarsBingBong** [comment]
Is still accurate? I'm on v0.3.0 of the tool - and it looks like its not updating.

**Comment by vladimirvivien** [comment]
Old issue, closing. Thanks for reporting it.
